### ISSUE TITLE
handling of high data rate

### ISSUE THREAD

**Issue by knelk** [daniilidis-group/mvsec#10]
Dear Zhu et al.,

thanks a lot for your amazing work! Currently I am involved in a project where we are recording high data rates (mostly visual input) and we have issues recording everything to disk without loosing too much information.

1) If you are willing, could you please shed some light on how you handeled the high data rate, e.g. which computer you used for recording? With all these sensors it seems like you must have more than one strong computer to write the data to disk.

2) Did you use the "traditional" rosbag.write() or rosbag.publish() mechanisms or you had to revert to high speed writing mechanisms as? Would you recommend them or do something different next time?

Thanks!

**Comment by alexzzhu** [comment]
Hi there,

Yes we definitely also ran into issues with data rates (and also power output from our laptop). Our laptop had two USB buses for the ports on opposite sides, so it ended up being ok to plug everything in to different ports with USB 3.0. We didn't run into issues writing to disk necessarily, we just used a Thinkpad laptop with an SSD. Perhaps your sensors are higher resolution/more in number than ours?

We used the standard publisher/subscriber mechanisms to generate/record data. The data was then recorded as a rosbag using the command line. I guess it is possible that some data was lost during this process, but we didn't notice anything egregious.

**Comment by knelk** [comment]
Dear Alex,

thanks a lot for this quick reply! With our planned setup, we should have a similar data load compared to you, but our recording is dropping a majority of events due to data overload.

> We used the standard publisher/subscriber mechanisms to generate/record data. 

Thanks, this is very helpful, we might just need to switch the computer ;)


Best
Simon
