### ISSUE TITLE
A question when played back the ***.bag

### ISSUE THREAD

**Issue by lunaWU628** [daniilidis-group/mvsec#13]
Hello, thank you for sharing this awesome dataset about the paper 《The Multivehicle Stereo Event Camera Dataset: An Event Camera Dataset for 3D Perception》
I am a graduate student from China, and I am currently learning about event camera. I want to look your dataset. I know they are composed of rosbag and need the rpg_dvs_ros package. I have successfully installed them, but when I downloaded a rosbag package and wanted to play it back, an error occurred: nothing can be played back.But I can play back the rosbag file which I recorded by myself.

Can you tell me what should I do, or am I missing what I need to view the rosbag?

I would be very grateful if you could reply to me.

**Comment by alexzzhu** [comment]
What is the error you're getting?

**Comment by lunaWU628** [comment]
Thanks for your reply.  What I mean is how to visualize the rosbag file you published. Is it visualized with this link：https://github.com/uzh-rpg/rpg_dvs_ros? 

I can play back the rosbag which I recored like this:
![Screenshot from 2022-01-06 14-46-44](https://user-images.githubusercontent.com/90367095/148341075-a6a5dcf8-fa34-43f1-912e-d2ce6e0df29e.png)

But I can't play back the rosbag which downloads from your dataset like this :
![Screenshot from 2022-01-06 14-47-43](https://user-images.githubusercontent.com/90367095/148341370-adc49a45-6298-40c5-bf94-17e23a3384ff.png)

I just learned this knowledge, any of your suggestions will be helpful to me, thank you

**Comment by alexzzhu** [comment]
Are you running the dvs_renderer node? That generates the rendered event image that you're visualizing.

**Comment by lunaWU628** [comment]
Yes, the above two pictures are running /dvs_rendering，but one has a image and the other has no image

**Comment by lunaWU628** [comment]
Could you please tell me how to view your rosbag file? I would very appreciate any advice from you. Thanks!

**Comment by alexzzhu** [comment]
Sorry for the late reply. I'm still a little unclear as to what you're running on your end. In order to generate visualizations under dvs_rendering, you need to run the dvs_renderer package from rpg_dvs_ros, and remap the event fields to match the ones in MVSEC (e.g. from events to /davis/left/events). Are you doing this already?

**Comment by lunaWU628** [comment]
Thank you very much for your reply, I will modify it according to your suggestion, thanks again！

**Comment by lunaWU628** [comment]
Thank you very much for your sincere help, I have been able to see your rosbag file like this :
![Screenshot from 2022-01-11 14-54-27](https://user-images.githubusercontent.com/90367095/148896204-31abe323-ece8-48e6-a959-52d496641b3d.png)

But I have a question: is this what the event camera and lidar look like when fused? Why can't I see any display about lidar?

Thanks again for the great dataset that you supplied.

**Comment by alexzzhu** [comment]
The rpg_dvs_ros package only visualizes event information. For visualizing the depths/event + depths, the other topics, such as /davis/left/blended_image_rect in the groundtruth file might be more useful.

**Comment by lunaWU628** [comment]
Thank you for your prompt reply and patient guidance.
