### ISSUE TITLE
Align VIsensor images with depth?

### ISSUE THREAD

**Issue by HTLeoo** [daniilidis-group/mvsec#19]
Hi, Alex,
I notice that in 'Unsupervised Event-based Learning of Optical Flow, Depth, and Egomotion', you use VI-Sensor grayscale images to train depth networks. I think the grayscale images and depth GT are temporally aligned, but it is confusing for me to align them in the spatial dimension. 
You provide calibration files, and I believe they can be used to transform points from VISensor frame coordinate to DAVIS frame coordinate. It is convenient for you to give a simple script to do this?

**Comment by alexzzhu** [comment]
Hi Haotian,

Do you mean to train depth networks for events (ala EV-FlowNet), or to train image based depth networks? For the latter, you can definitely transform the depths into the VI-Sensor frame, but it is indeed a little complicated with the transforms involved. I don't think I have the code anymore, but you can do this with the provided GT depths and the camera poses / extrinsics. 

The easiest way would be to directly transform the GT depths from the DAVIS frame to the VI-Sensor frame. Given each pixel in the DAVIS with a depth, you can project it to 3D in the DAVIS coordinate frame. Then use the transform between the VI-Sensor to DAVIS to transform the 3D point into the VI-Sensor frame, and then project back into 2D by dividing by the depth. I think the tricky part is getting the right transform from VI-Sensor to DAVIS where you might have it backward, but there should only be two combinations to try.

**Comment by HTLeoo** [comment]
@alexzzhu Thanks for your rapid reply!
I will try the approach you mentioned.
