### ISSUE TITLE
questions about indoor_flying dataset.

### ISSUE THREAD

**Issue by dlfksj** [daniilidis-group/mvsec#6]
Hi, 
First of all, thank you for sharing your dataset.
I have some questions about the indoor_flying data. 
I read the paper about the dataset, but I don't understand well. 

What I'm dealing with now is hdf5 file of indoor_flying, and these are my questions.
1. Is it right that '/davis/left/odometry' is the ground truth from LOAM 
    and '/davis/left/pose' is the ground truth from motion capture system?

2. What is the body frame of the indoor_flying set? Is it lidar or camera? 
    If not, where can I get the calibration matrix from body to camera/lidar frame?

Thank you so much.

**Comment by alexzzhu** [comment]
You are correct regarding the sources for the ground truths. The poses are all in camera frame, and the lidar to camera calibration can be found in the calibration yaml file.

**Comment by dlfksj** [comment]
Thank you for your reply.
