### ISSUE TITLE
Time synchronization between VI-sensor and DAVIS

### ISSUE THREAD

**Issue by tlkvstepan** [daniilidis-group/mvsec#9]
Hello Alex, 

Are timestamps of images from VI sensor and events from DAVIS sensors synchronized?
Can we, for example, get all events corresponding to the particular VI sensor image?

Best regards, Stepan

**Comment by alexzzhu** [comment]
Hi Stepan,

The timestamps were synchronized by aligning the gyroscope measurements from both sensors, which in turn are hardware synced to the images/events. Are you running into issues with the VI sensor data? We haven't tried using it for much in the past.

**Comment by tlkvstepan** [comment]
Hello Alex, 

Thank you for your reply. Good to know that they are synchronized! I have not started experimenting yet but if I find any issue I will let you know.
